---
- name: Build AMI for RStudio Connect
  hosts: localhost
  gather_facts: true
  become: true
  roles:
    - base
    - role: r
      vars:
        r_version: 4.0.3
    - python3
    - role: rstudio-connect
      vars:
        rstudio_connect_version: 1.8.6.2
